[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "4tLUmWg9ryR69hvLMeV9dttxiHemX2CEcQfzHi7FqizM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/parrotdev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
